"""empty message

Revision ID: 323a0f175f8b
Revises:
Create Date: 2015-04-09 16:12:44.899172

"""

# revision identifiers, used by Alembic.
revision = '323a0f175f8b'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():

    TYPES = (
        ('repo.push', 'Repository Push'),
    )

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_accounts',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('username', sa.UnicodeText(), nullable=False),
    sa.Column('password', sqlalchemy_utils.types.encrypted.EncryptedType(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('webhooks',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('event_type', sqlalchemy_utils.types.choice.ChoiceType(TYPES), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['webhook_accounts.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhooks')
    op.drop_table('webhook_accounts')
    ### end Alembic commands ###
